### ISSUE TITLE
Error: operator '>' has no left operand (PPC and ARM)

### ISSUE THREAD

**Issue by sagitter** [NumCosmo/NumCosmo#18]
Hi all.

I'm working to pack "numcosmo" for Fedora/EPEL7 that considers
additional architectures like PowerPC and ARM 64bit.

I noted an error when i build "numcosmo" on PPC and ARM32/64:

```
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -std=gnu99
-DHAVE_CONFIG_H -I. -I..    -Wall -fopenmp -DG_LOG_DOMAIN=\"NUMCOSMO\"
-pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
-D_REENTRANT -I/usr/include/cfitsio    -I../numcosmo/libcuba
-I../numcosmo/plc -I../numcosmo/plc/cldf -I../numcosmo/plc/minipmc
-I../numcosmo/plc/plik -I.. -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2
-fexceptions -fstack-protector-strong --param=ssp-buffer-size=4
-grecord-gcc-switches   -m64 -mcpu=power7 -mtune=power8 -c -o
math/ncm_mpsf_sbessel.lo math/ncm_mpsf_sbessel.c
math/ncm_func_eval.c: In function 'ncm_func_eval_get_pool':
math/ncm_func_eval.c:98:79: error: expected expression before ',' token
     _function_thread_pool = g_thread_pool_new (func, NULL,
NCM_THREAD_POOL_MAX, FALSE, &err);

      ^
math/ncm_func_eval.c: At top level:
math/ncm_func_eval.c:219:25: error: operator '>' has no left operand
 #if NCM_THREAD_POOL_MAX > 1
```

Can you take a look to this error please?

Full build log:
https://kojipkgs.fedoraproject.org//work/tasks/491/16180491/build.log

List of the dependencies:
https://kojipkgs.fedoraproject.org//work/tasks/491/16180491/root.log

Thanks.

**Comment by vitenti** [comment]
Hello,

This bug is caused by the failure of configure to detect correctly the
number of cores/cpus available. It will be fixed in the next release,
meanwhile, a simple fix is to pass the option --with-thread-pool-max=4
to the configure script, which is also a good idea for a generic release
since in this case there is no control on the number of cores that will
be available.

I also noticed that NLOpt are not included in the list of dependencies.
Even though it is a optional dependency, NumCosmo benefits greatly from
the advanced minimization algorithms present in this library, it may be a
good idea to include it.

Best,
Sandro Vitenti

**Comment by sagitter** [comment]
> This bug is caused by the failure of configure to detect correctly the
> number of cores/cpus available. It will be fixed in the next release,
> meanwhile, a simple fix is to pass the option --with-thread-pool-max=4
> to the configure script, which is also a good idea for a generic release
> since in this case there is no control on the number of cores that will
> be available.

Okay.

>I also noticed that NLOpt are not included in the list of dependencies.
Even though it is a optional dependency, NumCosmo benefits greatly from
the advanced minimization algorithms present in this library, it may be a
good idea to include it.

Unfortunately, NLOpt is built with G++ and looks incompatible with `numcosmo`.

**Comment by vitenti** [comment]
Do you mean that NLOpt fedora built was built with c++ support (configured with --with-cxx)? If so, why that makes it incompatible with numcosmo build? Note also that NLOpt can be built without c++ support and consequently with gcc instead of g++.

**Comment by sagitter** [comment]
I obtain this error by `configure`:

`configure: error: Can't link to -lnlopt. The nlopt library is probably compiled with c++ support, recompile the C version.
`

In Fedora:

```
$ rpm -q --list NLopt | grep lib
/usr/lib64/libnlopt_cxx.so.0
/usr/lib64/libnlopt_cxx.so.0.8.2
```

I have to ask a rebuild of `NLopt` to the package maintainer.

**Comment by vitenti** [comment]
Thanks. The NLopt maintainer can possibly produce a package containing both c++ and non-c++ libs. Nonetheless, if you send me the config.log produced by this configure run, I may be able to find a workaround.

**Comment by sagitter** [comment]
Of course:
[Uploading config.log.txt…]()

**Comment by sagitter** [comment]
This issue is resolved.
Thank you very much.
