### ISSUE TITLE
NcmSphereMap finish translation to GObject

### ISSUE THREAD

**Issue by pennalima** [NumCosmo/NumCosmo#2]
Currently part of the NcmSphereMap interface is written in GObject, but we still have to organize the code which stores the map conversions to spherical harmonics and pixel spaces.

**Comment by vitenti** [comment]
Most of the work was done, but there is still the need to include a fast Legendre polynomial calculator, a better test suit and documentation.

**Comment by vitenti** [comment]
Finished in last release!
