### ISSUE TITLE
Install error: 

### ISSUE THREAD

**Issue by yuanshuoastro** [NumCosmo/NumCosmo#29]
Dear NumCosmo Team,

I meet some error when "make install":

`
make  all-recursive
make[1]: Entering directory '/home/yuanshuo/works.cn2902/NumCosmo-0.13.3'
Making all in numcosmo
make[2]: Entering directory '/home/yuanshuo/works.cn2902/NumCosmo-0.13.3/numcosmo'
  GEN      ncm_enum_types.h
Traceback (most recent call last):
  File "/usr/bin/glib-mkenums", line 688, in <module>
    process_file(fname)
  File "/usr/bin/glib-mkenums", line 484, in process_file
    parse_entries(curfile, curfilename)
  File "/usr/bin/glib-mkenums", line 205, in parse_entries
    entries.append((name, value, options['nick']))
KeyError: 'nick'
Makefile:2791: recipe for target 'ncm_enum_types.h' failed
make[2]: *** [ncm_enum_types.h] Error 1
make[2]: Leaving directory '/home/yuanshuo/works.cn2902/NumCosmo-0.13.3/numcosmo'
Makefile:578: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/yuanshuo/works.cn2902/NumCosmo-0.13.3'
Makefile:466: recipe for target 'all' failed
make: *** [all] Error 2

`

Is there any suggestions?
Best

**Comment by vitenti** [comment]
Hello,

Newer versions of glib-mkenums (coming from newer GLib) introduced a bug in the parsing of enums. It assumes that all comments in the form /* < ... > */ in front of a enum item are either a skip or a nick definition, i.e., 
/* < skip > */
/* < nick=... > */.
So, when we mix with the  /* < private > */ comment of gtk-doc it breaks. 

A workaround was included in the commit: https://github.com/NumCosmo/NumCosmo/commit/9170bad3fc7a63da87540f157f4477223049d938 , unfortunately the current release 0.13.3 don't include it. You have two options, install from the repository (instructions here: https://numcosmo.github.io/download/ ) or wait a bit for a newer release (which I'll prepare ASAP) including this fix.

Best,
Sandro

**Comment by yuanshuoastro** [comment]
Thank you for your quick replay, @vitenti 
However, I tested the git repository:
`$git clone https://github.com/NumCosmo/NumCosmo.git
`

Then follow the instructions, but I recive another error during `make`:

Should I need to clone a certain branch or someting else I need to be careful on when git clone?


...
...
  CC       math/ncm_serialize.lo
  CC       math/ncm_obj_array.lo
  CC       math/ncm_integral1d.lo
  CC       math/ncm_integral1d_ptr.lo
  CC       math/ncm_rng.lo
  CC       math/ncm_qm_prop.lo
math/ncm_qm_prop.c: In function ‘_ncm_qm_prop_finalize’:
math/ncm_qm_prop.c:329:5: warning: implicit declaration of function ‘ARKodeFree’ [-Wimplicit-function-declaration]
     ARKodeFree (&self->arkode);
     ^
math/ncm_qm_prop.c: In function ‘_ncm_qm_prop_f’:
math/ncm_qm_prop.c:1474:3: error: unknown type name ‘sunindextype’
   sunindextype i;
   ^
math/ncm_qm_prop.c: In function ‘_ncm_qm_prop_J’:
math/ncm_qm_prop.c:1527:3: error: unknown type name ‘sunindextype’
   sunindextype i;
   ^
math/ncm_qm_prop.c: At top level:
math/ncm_qm_prop.c:1468:1: warning: ‘_ncm_qm_prop_f’ defined but not used [-Wunused-function]
 _ncm_qm_prop_f (gdouble t, N_Vector y, N_Vector ydot, gpointer user_data) 
 ^
math/ncm_qm_prop.c:1521:1: warning: ‘_ncm_qm_prop_J’ defined but not used [-Wunused-function]
 _ncm_qm_prop_J (N_Vector v, N_Vector Jv, gdouble t, N_Vector y, N_Vector fy, gp
 ^
Makefile:2435: recipe for target 'math/ncm_qm_prop.lo' failed
make[4]: *** [math/ncm_qm_prop.lo] Error 1
make[4]: Leaving directory '/home/yuanshuo/works.cn2902/NumCosmo/numcosmo'
Makefile:2570: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/yuanshuo/works.cn2902/NumCosmo/numcosmo'
Makefile:1641: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/yuanshuo/works.cn2902/NumCosmo/numcosmo'
Makefile:594: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/yuanshuo/works.cn2902/NumCosmo'
Makefile:482: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vitenti** [comment]
The HEAD version was lacking the conditional compilation of some parts that require a newer version of Sundials. Anyway, the new release (and repo's HEAD) should work.

**Comment by yuanshuoastro** [comment]
@vitenti  Thank you very much!
