### ISSUE TITLE
prepare() fails locally

### ISSUE THREAD

**Issue by EFrion** [NumCosmo/NumCosmo#50]
Hi NumCosmo users,

I am trying to run the contents of the MagDustBounce.ipynb notebook locally on my own computer, but I have an issue with the prepare() function. What I do is simply copying the notebook's contents up to the first plot (giving a file named MagDustModeEvol.pdf), and run it with python3. In the code, we create a class called csq1d, and at some point we call a function ```csq1d.prepare()``` which fails, returning the error  ```NUMCOSMO:ERROR:math/ncm_csq1d.c:2164:ncm_csq1d_prepare: assertion failed: (self->init_cond_set)```
Running the notebook with binder works fine, so I am a bit lost concerning why this error appears. Any thoughts?

Thanks a lot!
Manu

**Comment by EFrion** [comment]
Ok, it seems that I just needed to add the line ```csq1d.set_init_cond_adiab (None, ti)```. It makes sense, but I am still confused why the notebook runs with binder without it... Anyway, it runs nows!

**Comment by vitenti** [comment]
Hello, @EFrion we are adding new ways to define initial conditions (besides the adiabatic vacuum), for this reason now the user must specify explicitly the initial conditions. The version on binder is the older one, that's way it still works without this line.
