### ISSUE TITLE
Remodel Galaxy WL object structure

### ISSUE THREAD

**Issue by caioolivv** [NumCosmo/NumCosmo#91]
Currently WL analysis is done by creating GalaxyWL objects containing GalaxyWLDist and GalaxyRedshift objects. Since shape and position information are grouped in the same object, separated from redshift data, binning processes are not straight forward. It also presents a difficulty if we were to hierarchically sample information for kernel density estimation and forward modelling. These problems would be avoided if we rewrote the WL likelihood the objects in the following structure

- `NcGalaxyWL` object which would contain the following objects:
  - `NcGalaxySampleDistributionPosition` with information on image position and redshift;
  - `NcGalaxySampleDistributionShape` with information on intrinsic shape, observed shape and the shear mapping (this might also be capable of holding information on measuring error);
  - `NcGalaxySampleDistributionZProxy` with information on proxy redshift;

Mathematically, the above objects would represent the likelihood

$$\mathcal{P} (\epsilon, r, z_p) = \int dz dr \mathcal{P}(\epsilon | z, r, \theta) \mathcal{P}(z_p | z, \theta ) \mathcal{P} (r | \theta) \mathcal{P} (z | \theta),$$

with the following map

- `NcGalaxyWL` -> $\mathcal{P} (\epsilon, r, z_p)$;
- `NcGalaxySampleDistributionPosition` -> $\mathcal{P} (r | \theta) \mathcal{P} (z | \theta)$;
- `NcGalaxySampleDistributionShape` -> $\mathcal{P}(\epsilon | z, r, \theta)$;
- `NcGalaxySampleDistributionZProxy` -> $\mathcal{P}(z_p | z, \theta )$;

Also, we might also use `GSD` instead of `GalaxySampleDistribution`.

**Comment by vitenti** [comment]
The object structure is fine. The name can be `GalaxySDPosition` that is instead of `GalaxySampleDistribution` or `GSD` we can use `GalaxySD`. What do you think?

**Comment by vitenti** [comment]
Done in #165
